apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubrowser-backend
  namespace: kubrowser
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubrowser-backend
  namespace: kubrowser
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubrowser-backend
  namespace: kubrowser
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubrowser-backend
subjects:
  - kind: ServiceAccount
    name: kubrowser-backend
    namespace: kubrowser
