apiVersion: v1
kind: Service
metadata:
  name: kubrowser-backend
  namespace: kubrowser
spec:
  selector:
    app: kubrowser-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: kubrowser-frontend
  namespace: kubrowser
spec:
  selector:
    app: kubrowser-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
